---
title: "Welcome 👋"
---

Welcome to the lab *"prompt engineering"* 

In this lab, we will use OpenAI's API access to leverage Large Language Models (LLMs) like *GPT-3.5 Turbo* and *GPT-4* into custom Python applications, and learn how to build our own chatbot.

::: {.callout-important}
Make sure you meet all the [requirements](/requirements.qmd) and have read the lecture [slides](/slide.qmd) before you start with the [assignments](/assignments.qmd) 
:::

What you will learn in this lab:

- You'll practice prompting principles and their related tactics 
- How to analyze and refine your prompts to generate marketing copy from a product fact sheet.
- Summarize text with a focus on specific topics.
- Infer sentiment and topics from product reviews and news articles.
- Explore how to use Large Language Models for text transformation tasks such as language translation, spelling and grammar checking, tone adjustment, and format conversion.
- Generate customer service emails that are tailored to each customer's review.
- How you can utilize the chat format to have extended conversations with chatbots personalized or specialized for specific tasks or behaviors.


---

*This lab is mainly based on an excellent course provided by Isa Fulford from OpenAI and Andrew Ng from DeepLearning.AI.*