---
title: "Slides"
number-sections: true
---


::: {.callout-note appearance="simple"}
Take a look at the [slides tutorial](https://kirenz.github.io/lab-toolkit/slides/slides.html#/title-slide) to learn how to use all slide options. 
:::

You have several options to start code development:

1. **Colab**: Click on one of the links "💻 Jupyter Notebook" to start a Colab session. 

2. **Local**: Click on one of the links "💻 Jupyter Notebook" below, go to the Colab menu and choose "File" > "Download" > "Download .ipynb"

3. **Cloud Codespace**: Work in a fully configured dev environment in the cloud with a [GitHub Codespace VS Code Browser](https://github.com/kirenz/lab-prompt/blob/main/README.md) environment.

4. **Local VS Code with Codespace**: Use [GitHub Codespaces in your local Visual Studio Code environment](https://docs.github.com/en/codespaces/developing-in-codespaces/using-github-codespaces-in-visual-studio-code).


For cost reasons we mainly use OpenAI's `gpt-3.5-turbo` model in our tutorials. Note the [price differences](https://openai.com/pricing) between the models.


# Guidelines

In this tutorial, you'll practice two prompting principles and their related tactics in order to write effective prompts for large language models:


::: {.callout-tip appearance="simple" icon=false}
- [🖥️ Presentation](/slides/guidelines.qmd)
- [💻 Jupyter Notebook](https://colab.research.google.com/github/kirenz/lab-prompt/blob/main/code/guidelines.ipynb)
:::



# Iterative prompt development

In this tutorial, you'll iteratively analyze and refine your prompts to generate marketing copy from a product fact sheet.

::: {.callout-tip appearance="simple" icon=false}
- [🖥️ Presentation](/slides/iterative-prompt-development.qmd)
- [💻 Jupyter Notebook](https://colab.research.google.com/github/kirenz/lab-prompt/blob/main/code/iterative-prompt-development.ipynb)
:::


# Summarize text

In this tutorial, you will summarize text with a focus on specific topics.

::: {.callout-tip appearance="simple" icon=false}
- [🖥️ Presentation](/slides/summarizing.qmd)
- [💻 Jupyter Notebook](https://colab.research.google.com/github/kirenz/lab-prompt/blob/main/code/summarizing.ipynb)
:::


# Inferring

In this tutorial, you will infer sentiment and topics from product reviews and news articles.

::: {.callout-tip appearance="simple" icon=false}
- [🖥️ Presentation](/slides/inferring.qmd)
- [💻 Jupyter Notebook](https://colab.research.google.com/github/kirenz/lab-prompt/blob/main/code/inferring.ipynb)
:::

# Transforming

In this presentation, we will explore how to use Large Language Models for text transformation tasks such as language translation, spelling and grammar checking, tone adjustment, and format conversion.

::: {.callout-tip appearance="simple" icon=false}
- [🖥️ Presentation](/slides/transforming.qmd)
- [💻 Jupyter Notebook](https://colab.research.google.com/github/kirenz/lab-prompt/blob/main/code/transforming.ipynb)
:::


# Expanding

In this tutorial, you will generate customer service emails that are tailored to each customer's review.

::: {.callout-tip appearance="simple" icon=false}
- [🖥️ Presentation](/slides/expanding.qmd)
- [💻 Jupyter Notebook](https://colab.research.google.com/github/kirenz/lab-prompt/blob/main/code/expanding.ipynb)
:::


## Chatbot

In this presentation, you will explore how you can utilize the chat format to have extended conversations with chatbots personalized or specialized for specific tasks or behaviors.

<!--
We use [Panel](https://panel.holoviz.org/), an open-source Python library that lets you easily build powerful tools, dashboards and complex applications entirely in Python. 
-->

::: {.callout-tip appearance="simple" icon=false}
- [🖥️ Presentation](/slides/chatbot.qmd)
- [💻 Jupyter Notebook](https://colab.research.google.com/github/kirenz/lab-prompt/blob/main/code/chatbot.ipynb)
:::

